import { useSession, signIn, signOut } from "next-auth/react"
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function Home() {
  const { data: session, loadingSession } = useSession();
  console.log(session)

  if (session) {
    return (
      <div data-theme="dark" className={styles.container}>
        <button className="btn btn-circle">jsofjl</button>
        Welcome user<br />
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    );
  }
  return (
    <div className={styles.container} data-theme="dark">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      <button onClick={() => signIn()}>Sign in</button>
    </div>
  );
}