import { useSession, signIn, signOut } from "next-auth/react"
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function Home() {
  const { data: session, loadingSession } = useSession();
  console.log(session)
  
  if (session) {
    return (
      <div className={styles.container}>
        Welcome user<br />
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Click to sign into your user account <br />
      <button onClick={() => signIn()}>Sign in</button>
    </div>
  );
}